# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/ubuntu/.devcontainer/base.Dockerfile


FROM rust:latest

COPY . .

RUN cargo install --path ./api/functions/image-grayscale